<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComputerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerRepository extends EntityRepository
{
    public function setEnableAll($enabled)
    {
        // todo :
    }
}
