services:
    park.twig.computer_status_extension:
        class: AppBundle\Twig\ComputerStatusExtension
        tags:
            - { name: twig.extension }
    park.computer_manager:
        class: AppBundle\Services\ComputerManager
        arguments: [@doctrine.orm.entity_manager]

    park.calculator:
        class: AppBundle\Services\Calculator